import { transpileWithPlugins } from "../testing";

import { plugin } from "./plugin";

describe("built_at_info plugin", () => {
  it("should prepend build timestamp comments", () => {
    const { errors, lua } = transpileWithPlugins(
      {
        "main.ts": `
export const value = 1;
`,
      },
      { plugins: [plugin] }
    );
    const normalized = lua["main.lua"].replace(
      /^-- Generated by xrf util at: .+\n\n/,
      "-- Generated by xrf util at: <timestamp>\n\n"
    );

    expect(errors).toEqual([]);
    expect(normalized).toBe(`-- Generated by xrf util at: <timestamp>

local ____exports = {}
____exports.value = 1
return ____exports
`);
  });

  it("should prepend the timestamp comment to every emitted file", () => {
    const { errors, lua } = transpileWithPlugins(
      {
        "first.ts": `export const a = 1;`,
        "second.ts": `export const b = 2;`,
      },
      { plugins: [plugin] }
    );
    const stamp = /^-- Generated by xrf util at: .+\n\n/;

    expect(errors).toEqual([]);
    expect(lua["first.lua"]).toMatch(stamp);
    expect(lua["second.lua"]).toMatch(stamp);
    expect(lua["first.lua"].replace(stamp, "")).toBe(`local ____exports = {}
____exports.a = 1
return ____exports
`);
    expect(lua["second.lua"].replace(stamp, "")).toBe(`local ____exports = {}
____exports.b = 2
return ____exports
`);
  });
});
