import * as path from "path";

import { isIdentifier, type Program, SyntaxKind } from "typescript";
import * as lua from "typescript-to-lua";
import {
  type CompilerOptions,
  createStringLiteral,
  type EmitFile,
  type EmitHost,
  type Plugin,
} from "typescript-to-lua";

import { createErrorDiagnosticFactory } from "../utils/diagnostics";

const MACROS_MODULE: string = "xray16/macros";

const FILENAME_IDENTIFIER: string = "$filename";
const DIRNAME_IDENTIFIER: string = "$dirname";

const FROM_CAST_METHODS: Array<string> = ["$fromObject", "$fromArray", "$fromLuaArray", "$fromLuaTable"];
const NIL_CHECK_METHODS: Map<string, lua.BinaryOperator> = new Map([
  ["$isNil", lua.SyntaxKind.EqualityOperator],
  ["$isNotNil", lua.SyntaxKind.InequalityOperator],
]);

/**
 * Push generic error to notify about cast helper usage issue.
 */
const createInvalidFunctionCallError = createErrorDiagnosticFactory(() => {
  return `Invalid transformer call, expected function to have exactly 1 argument.`;
});

/**
 * Configuration for the macros plugin, provided verbatim from the tsconfig `luaPlugins` entry.
 *
 * All features default to enabled; the token-driven ones are inert unless the matching `$` token is used.
 */
export interface IMacrosPluginConfig {
  /** Prepend a build timestamp comment to every emitted file. Defaults to `true`. */
  buildTimestamp?: boolean;
  /** Replace `$filename` with the compile-time file name. Defaults to `true`. */
  fileName?: boolean;
  /** Replace `$dirname` with the compile-time directory name. Defaults to `true`. */
  dirName?: boolean;
  /** Expand `$fromObject`/`$fromArray`/`$fromLuaArray`/`$fromLuaTable`/`$isNil`/`$isNotNil` helpers. Defaults to `true`. */
  castHelpers?: boolean;
}

/**
 * Create a plugin that applies compile-time macros: file metadata tokens, cast helpers and a build header.
 *
 * @param config - Selection of which macro features are enabled.
 * @returns Configured TypeScriptToLua plugin.
 */
export function createPlugin(config: IMacrosPluginConfig = {}): Plugin {
  const injectFileName: boolean = config.fileName ?? true;
  const injectDirName: boolean = config.dirName ?? true;
  const castHelpers: boolean = config.castHelpers ?? true;
  const buildTimestamp: boolean = config.buildTimestamp ?? true;

  const plugin: Plugin = {
    visitors: {
      [SyntaxKind.ImportDeclaration]: (node, context) => {
        // Runtime helpers are imported from `xray16/macros` so the code runs under jest/node without
        // globals or mocks; the import has no runtime counterpart in the emitted Lua, so drop it.
        if (node.moduleSpecifier.getText().slice(1, -1) === MACROS_MODULE) {
          return undefined;
        }

        return context.superTransformStatements(node);
      },
      [SyntaxKind.Identifier]: (node, context) => {
        if (injectFileName && node.text === FILENAME_IDENTIFIER) {
          return createStringLiteral(path.parse(context.sourceFile.fileName).name);
        }

        if (injectDirName && node.text === DIRNAME_IDENTIFIER) {
          return createStringLiteral(path.basename(path.dirname(context.sourceFile.fileName)));
        }

        return context.superTransformExpression(node);
      },
      [SyntaxKind.CallExpression]: (node, context) => {
        if (castHelpers && isIdentifier(node.expression) && FROM_CAST_METHODS.includes(node.expression.text)) {
          if (node.arguments.length !== 1) {
            context.diagnostics.push(createInvalidFunctionCallError(node));
          }

          return context.transformExpression(node.arguments[0]);
        }

        if (castHelpers && isIdentifier(node.expression) && NIL_CHECK_METHODS.has(node.expression.text)) {
          if (node.arguments.length !== 1) {
            context.diagnostics.push(createInvalidFunctionCallError(node));

            return context.superTransformExpression(node);
          }

          return lua.createBinaryExpression(
            context.transformExpression(node.arguments[0]),
            lua.createNilLiteral(node),
            NIL_CHECK_METHODS.get(node.expression.text) as lua.BinaryOperator,
            node
          );
        }

        return context.superTransformExpression(node);
      },
    },
  };

  if (buildTimestamp) {
    const comment: string = `-- Generated by xrf util at: ${new Date().toString()}\n\n`;

    plugin.beforeEmit = (program: Program, options: CompilerOptions, emitHost: EmitHost, result: Array<EmitFile>) => {
      for (const file of result) {
        file.code = comment + file.code;
      }
    };
  }

  return plugin;
}
